local QBCore,ESX
local framework=Config.Framework
local rules={}
local function detect() if framework=='auto'then if GetResourceState('qbx_core')=='started'then framework='qbox'elseif GetResourceState('qb-core')=='started'then framework='qb'elseif GetResourceState('es_extended')=='started'then framework='esx'else framework='standalone'end end;if framework=='qb'then QBCore=exports['qb-core']:GetCoreObject()elseif framework=='esx'then ESX=exports['es_extended']:getSharedObject()end;print('[Blackpool Threads] framework='..framework)end
CreateThread(detect)
local function player(src)if framework=='qbox'then return exports.qbx_core:GetPlayer(src)elseif framework=='qb'then return QBCore.Functions.GetPlayer(src)elseif framework=='esx'then return ESX.GetPlayerFromId(src)end end
local function ident(src)local p=player(src);if framework=='qbox'or framework=='qb'then return p and p.PlayerData.citizenid elseif framework=='esx'then return p and p.identifier end;return GetPlayerIdentifierByType(src,'license')end
local function job(src)local p=player(src);if framework=='qbox'or framework=='qb'then local j=p and p.PlayerData.job;return j and j.name or'unemployed',j and j.grade and tonumber(j.grade.level)or 0 elseif framework=='esx'then local j=p and p.getJob();return j and j.name or'unemployed',j and tonumber(j.grade)or 0 end;return'unemployed',0 end
local function admin(src)if src==0 then return true end;if IsPlayerAceAllowed(src,Config.AdminAce or'blackpoolthreads.admin')then return true end;for _,a in ipairs({'admin','god','mod','command'})do if IsPlayerAceAllowed(src,a)then return true end end;return false end
local function key(p,i,t)return p..'|'..i..'|'..tostring(t)end
local function load()rules={};for _,r in ipairs(MySQL.query.await('SELECT * FROM mj_clothing_rules')or{})do r.jobs=r.jobs and json.decode(r.jobs)or{};rules[key(r.ped_model,r.item_id,r.texture)]=r end end
CreateThread(function()Wait(1000);load()end)
local function rule(p,i,t)return rules[key(p,i,t)]or rules[key(p,i,-1)]or{state='available',jobs={}}end
local function access(src,p,i,t)local r=rule(p,i,t);if r.state=='blacklisted'then return false,r elseif r.state=='restricted'then local j,g=job(src);local m=r.jobs and r.jobs[j];return m~=nil and g>=tonumber(m),r end;return true,r end
local function respond(src,id,d)TriggerClientEvent('mj-clothing:response',src,id,d)end
local function removeMoney(src,n)local p=player(src);if framework=='qbox'then return exports.qbx_core:RemoveMoney(src,'bank',n,'clothing-purchase')elseif framework=='qb'then return p and p.Functions.RemoveMoney('bank',n,'clothing-purchase')or false elseif framework=='esx'then if not p or p.getAccount('bank').money<n then return false end;p.removeAccountMoney('bank',n,'Clothing purchase');return true end;return true end
RegisterNetEvent('mj-clothing:getWardrobe',function(id)local src=source;local owner=ident(src);if not owner then return respond(src,id,{items={}})end;local rows=MySQL.query.await('SELECT id,item_id,item_data,purchased_at FROM mj_clothing_owned WHERE owner=? ORDER BY id DESC',{owner})or{};local out={};for _,r in ipairs(rows)do local ok,d=pcall(json.decode,r.item_data or'{}');if ok and type(d)=='table'then d.ownedId=r.id;d.id=d.id or r.item_id;d.purchasedAt=r.purchased_at;d.owned=true;out[#out+1]=d end end;respond(src,id,{items=out})end)
RegisterNetEvent('mj-clothing:getAdminCatalogue',function(id,payload)local src=source;if not admin(src)then return respond(src,id,{allowed=false,message='No clothing admin permission.'})end;local out={};for _,r in pairs(rules)do if r.ped_model==payload.pedModel then out[key(r.ped_model,r.item_id,r.texture)]={itemId=r.item_id,texture=r.texture,state=r.state,jobs=r.jobs,note=r.note}end end;local jobs={};if framework=='qbox'then local ok,d=pcall(function()return exports.qbx_core:GetJobs()end);if ok and d then for n,j in pairs(d)do jobs[#jobs+1]={name=n,label=j.label or n}end end elseif framework=='qb'and QBCore then for n,j in pairs(QBCore.Shared.Jobs or{})do jobs[#jobs+1]={name=n,label=j.label or n}end elseif framework=='esx'then for n,j in pairs(ESX.GetJobs()or{})do jobs[#jobs+1]={name=n,label=j.label or n}end end;respond(src,id,{allowed=true,rules=out,jobs=jobs})end)
local function saveRule(src,ped,r)if not admin(src)then return false,'No permission'end;if not r or not r.itemId or not({available=true,restricted=true,blacklisted=true})[r.state]then return false,'Invalid rule'end;local t=tonumber(r.texture)or-1;local jobs=r.state=='restricted'and(r.jobs or{})or{};local old=rule(ped,r.itemId,t);local who=ident(src)or'unknown';local name=GetPlayerName(src)or'console';local jj=json.encode(jobs);MySQL.prepare.await('INSERT INTO mj_clothing_rules (ped_model,item_id,texture,state,jobs,note,updated_by) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE state=VALUES(state),jobs=VALUES(jobs),note=VALUES(note),updated_by=VALUES(updated_by)',{ped,r.itemId,t,r.state,jj,r.note,who});MySQL.insert.await('INSERT INTO mj_clothing_audit (admin_identifier,admin_name,ped_model,item_id,texture,old_state,new_state,jobs,note) VALUES (?,?,?,?,?,?,?,?,?)',{who,name,ped,r.itemId,t,old.state,r.state,jj,r.note});rules[key(ped,r.itemId,t)]={ped_model=ped,item_id=r.itemId,texture=t,state=r.state,jobs=jobs,note=r.note};return true,'Saved'end
RegisterNetEvent('mj-clothing:adminSaveRule',function(id,p)local ok,msg=saveRule(source,p.pedModel,p.rule);respond(source,id,{ok=ok,message=msg,rule=p.rule})end)
RegisterNetEvent('mj-clothing:adminBulkSave',function(id,p)local src=source;if not admin(src)then return respond(src,id,{ok=false,message='No permission'})end;local c=0;for _,r in ipairs(p.rules or{})do if saveRule(src,p.pedModel,r)then c=c+1 end end;respond(src,id,{ok=true,message=('Saved %s rules'):format(c)})end)
RegisterNetEvent('mj-clothing:purchase',function(cart)local src=source;if type(cart)~='table'or#cart==0 or#cart>(Config.MaxBasketItems or20)then return end;local clean,total={},0;for _,line in ipairs(cart)do local slot;for _,s in ipairs(Config.Scan or{})do if s.type==line.type and s.component==tonumber(line.component)then slot=s break end end;local d,t=tonumber(line.drawable),tonumber(line.texture);local p=line.pedModel or'mp_m_freemode_01';local ok=slot and d and t and access(src,p,line.id,t);if ok then total=total+slot.price;clean[#clean+1]={id=line.id,name=line.name,category=line.category,type=line.type,component=tonumber(line.component),drawable=d,texture=t,textures={t},colours={line.colour or('Texture '..t)},price=slot.price,pedModel=p}end end;if#clean~=#cart then return TriggerClientEvent('mj-clothing:purchaseResult',src,false,'Basket contains unavailable clothing')end;if not removeMoney(src,total)then return TriggerClientEvent('mj-clothing:purchaseResult',src,false,'Not enough money')end;local owner=ident(src);for _,i in ipairs(clean)do MySQL.insert.await('INSERT INTO mj_clothing_owned (owner,item_id,item_data) VALUES (?,?,?)',{owner,i.id,json.encode(i)})end;TriggerClientEvent('mj-clothing:purchaseResult',src,true,('Purchase complete: £%s'):format(total),clean)end)
RegisterNetEvent('mj-clothing:requestRuleSummary',function(p)local src=source;local c=0;for _,r in pairs(rules)do if r.ped_model==p then c=c+1 end end;TriggerClientEvent('chat:addMessage',src,{args={'Blackpool Threads',('Loaded %s clothing rules'):format(c)}})end)
RegisterCommand('clothingstatus',function(src)local m='Blackpool Threads running; framework='..framework;if src==0 then print(m)else TriggerClientEvent('chat:addMessage',src,{args={'Blackpool Threads',m}})end end,false)
