const state={catalogue:[],category:'',selected:null,textureIndex:0,cart:[],owned:[],favourites:[],currency:'£',query:'',page:0,pageSize:4,mode:'shop',rules:{},jobs:[],adminState:'available'};
const $=s=>document.querySelector(s);const resource=()=>typeof GetParentResourceName==='function'?GetParentResourceName():'mj-clothing-v2-blackpool-threads';
const post=(name,data={})=>fetch(`https://${resource()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).catch(()=>{});const money=n=>state.currency+n;
function toast(text){const e=$('#toast');e.textContent=text;e.style.display='block';setTimeout(()=>e.style.display='none',1400)}

function ruleKey(itemId,texture=-1){return `${state.pedModel||''}|${itemId}|${texture}`}
function itemRule(item,texture=-1){return state.rules[ruleKey(item.id,texture)]||state.rules[`${state.pedModel||''}|${item.id}|-1`]||{state:'available',jobs:{},note:''}}
function openAdminRule(item){if(state.mode!=='admin')return;state.selected=item;preview();const r=itemRule(item,-1);state.adminState=r.state||'available';$('#adminItemTitle').textContent=item.name;$('#adminItemId').textContent=`${item.type} • component ${item.component} • drawable ${item.drawable}`;$('#adminTexture').innerHTML='<option value="-1">Entire drawable</option>'+item.textures.map((t,i)=>`<option value="${t}">Texture ${i+1} (${t})</option>`).join('');$('#adminNote').value=r.note||'';renderAdminJobs(r.jobs||{});syncAdminState();$('#adminDrawer').classList.remove('hidden')}
function renderAdminJobs(selected){$('#adminJobs').innerHTML=state.jobs.map(j=>`<div class="job-row"><input type="checkbox" data-jobcheck="${j.name}" ${selected[j.name]!==undefined?'checked':''}><span>${j.label} <small>${j.name}</small></span><input type="number" min="0" value="${selected[j.name]??0}" data-jobgrade="${j.name}"></div>`).join('')||'<div class="admin-id">No framework jobs returned. Enter jobs after adding them to the framework.</div>'}
function syncAdminState(){document.querySelectorAll('[data-state]').forEach(b=>b.classList.toggle('active',b.dataset.state===state.adminState));$('#jobSection').classList.toggle('hidden',state.adminState!=='restricted')}

function filtered(){return state.catalogue.filter(x=>x.category===state.category&&x.name.toLowerCase().includes(state.query.toLowerCase()))}
function pages(){return Math.max(1,Math.ceil(filtered().length/state.pageSize))}
function clampPage(){state.page=Math.max(0,Math.min(state.page,pages()-1))}
function choose(x){state.selected=x;state.textureIndex=0;preview();renderSelected();renderGrid();if(state.mode==='admin')openAdminRule(x)}
function renderCategories(){const cats=[...new Set(state.catalogue.map(x=>x.category))];$('#categories').innerHTML=cats.map(c=>`<button class="${c===state.category?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;state.page=0;state.query='';$('#search').value='';state.selected=state.catalogue.find(x=>x.category===state.category)||null;state.textureIndex=0;post('cameraCategory',{category:state.category});preview();render()})}
function renderSelected(){const x=state.selected;if(!x){$('#selectedBox').innerHTML='';return}$('#selectedBox').innerHTML=`<b>${x.name}${state.owned.includes(x.id)?' • OWNED':''}</b><strong>${money(x.price)}</strong><div class="swatches">${x.colours.map((c,i)=>`<button data-texture="${i}" class="${i===state.textureIndex?'active':''}">${c}</button>`).join('')}</div>`;document.querySelectorAll('[data-texture]').forEach(b=>b.onclick=()=>{state.textureIndex=+b.dataset.texture;preview();renderSelected()})}
function renderGrid(direction=0){clampPage();const all=filtered(),start=state.page*state.pageSize,items=all.slice(start,start+state.pageSize);const grid=$('#grid');grid.style.opacity='0';grid.style.transform=`translateX(${direction*12}px)`;setTimeout(()=>{grid.innerHTML=items.length?items.map(x=>`<button class="card ${state.selected?.id===x.id?'active':''}" data-id="${x.id}"><span class="status-dot status-${itemRule(x,-1).state}"></span><div class="thumb">${x.category[0]}</div><b>${x.name}</b><small>${x.colours.length} textures</small><strong>${money(x.price)}</strong></button>`).join(''):'<div class="empty-cards">No matching clothing</div>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>choose(state.catalogue.find(x=>x.id===b.dataset.id)));grid.style.transform=`translateX(${-direction*12}px)`;requestAnimationFrame(()=>{grid.style.opacity='1';grid.style.transform='translateX(0)'})},90);$('#pageStatus').textContent=`${state.page+1} / ${pages()}`;$('#pagePrev').disabled=state.page===0;$('#pageNext').disabled=state.page>=pages()-1}
function renderCart(){const e=$('#cart');e.innerHTML=state.cart.length?state.cart.map((x,i)=>`<div class="line"><div class="line-top"><div><b>${x.name}</b><br><small>${x.colour} • ${money(x.price)}</small></div><button data-remove="${i}">×</button></div><div class="line-bottom"><span>Individual piece</span><b>${money(x.price)}</b></div></div>`).join(''):'<div class="empty">Your basket is empty.<br>Build a fit.</div>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.cart.splice(+b.dataset.remove,1);renderCart()});const total=state.cart.reduce((n,x)=>n+x.price,0);$('#total').textContent=money(total);$('#itemCount').textContent=`${state.cart.length} item${state.cart.length===1?'':'s'}`;$('#purchase').disabled=!state.cart.length}
function render(){renderCategories();renderSelected();renderGrid();renderCart();$('#crumb').textContent=`${state.mode==='wardrobe'?'WARDROBE':'SHOP'} / ${state.category.toUpperCase()}`;$('#ownedCount').textContent=state.mode==='wardrobe'?state.catalogue.length:state.owned.length;$('#add').style.display=state.mode==='wardrobe'?'none':'';$('#purchase').style.display=state.mode==='wardrobe'?'none':'';}
function preview(){if(state.selected)post('preview',{item:state.selected,textureIndex:state.textureIndex})}
$('#search').oninput=e=>{state.query=e.target.value;state.page=0;renderGrid(1)};$('#pagePrev').onclick=()=>{if(state.page>0){state.page--;renderGrid(-1)}};$('#pageNext').onclick=()=>{if(state.page<pages()-1){state.page++;renderGrid(1)}};
$('#wardrobeOpen').onclick=()=>post('openWardrobe');
$('#add').onclick=()=>{const x=state.selected;if(!x||state.mode==='wardrobe')return;state.cart.push({id:x.id,name:x.name,category:x.category,type:x.type,component:x.component,drawable:x.drawable,texture:x.textures[state.textureIndex],textureIndex:state.textureIndex,price:x.price,colour:x.colours[state.textureIndex],pedModel:state.pedModel});renderCart();toast('Added to basket')};
$('#favourite').onclick=()=>{const id=state.selected?.id;if(!id)return;state.favourites=state.favourites.includes(id)?state.favourites.filter(x=>x!==id):[...state.favourites,id];$('#favourite').textContent=state.favourites.includes(id)?'♥':'♡'};$('#purchase').onclick=()=>post('purchase',{cart:state.cart});$('#reset').onclick=()=>post('resetPreview');document.querySelectorAll('[data-rotate]').forEach(b=>b.onclick=()=>post('rotate',{amount:+b.dataset.rotate}));document.addEventListener('keydown',e=>{if(e.key==='Escape')post('close');if(e.key==='ArrowLeft')$('#pagePrev').click();if(e.key==='ArrowRight')$('#pageNext').click()});
window.addEventListener('message',e=>{const d=e.data;if(d.action==='open'){state.catalogue=d.catalogue||[];state.currency=d.currency||'£';state.mode=d.mode||'shop';state.rules=d.rules||{};state.jobs=d.jobs||[];state.pedModel=d.pedModel||'';if(state.mode==='wardrobe')state.owned=state.catalogue.map(x=>x.id);$('#app').classList.toggle('admin-mode',state.mode==='admin');state.category=state.catalogue[0]?.category||'Tops';state.selected=state.catalogue[0]||null;state.cart=[];state.page=0;state.query='';$('#search').value='';$('#app').classList.remove('hidden');post('cameraCategory',{category:state.category});render()}if(d.action==='catalogueUpdate'&&d.catalogue){state.catalogue=d.catalogue;state.selected=state.catalogue.find(x=>x.id===state.selected?.id)||state.catalogue[0]||null;render()}if(d.action==='close')$('#app').classList.add('hidden');if(d.action==='adminSaveResult'){toast(d.result?.message||'Saved');if(d.result?.ok&&d.result.rule){state.rules[ruleKey(d.result.rule.itemId,d.result.rule.texture)]=d.result.rule;renderGrid();$('#adminDrawer').classList.add('hidden')}}if(d.action==='purchaseResult'){toast(d.message||'Done');if(d.ok){state.owned=[...new Set([...state.owned,...(d.purchased||[]).map(x=>x.id)])];state.cart=[];render()}}});
document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{state.adminState=b.dataset.state;syncAdminState()});
$('#adminClose').onclick=()=>$('#adminDrawer').classList.add('hidden');
$('#adminTexture').onchange=()=>{const r=itemRule(state.selected,+$('#adminTexture').value);state.adminState=r.state||'available';$('#adminNote').value=r.note||'';renderAdminJobs(r.jobs||{});syncAdminState()};
$('#adminSave').onclick=()=>{const jobs={};document.querySelectorAll('[data-jobcheck]:checked').forEach(c=>{jobs[c.dataset.jobcheck]=+document.querySelector(`[data-jobgrade="${c.dataset.jobcheck}"]`).value||0});const rule={itemId:state.selected.id,texture:+$('#adminTexture').value,state:state.adminState,jobs,note:$('#adminNote').value};post('adminSaveRule',rule);};
